name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Verify dockefiles are up-to-date
      run: |
        cmake .
        make -j$(nproc)
        git diff --exit-code

  encoder-selfbuild-prodkmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/encoder/ubuntu22.04/selfbuild-prodkmd/Dockerfile --tag cloud-encoder .

  encoder-intel-gfx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/encoder/ubuntu22.04/intel-gfx/Dockerfile --tag cloud-encoder .

  streamer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/streamer/ubuntu22.04/Dockerfile --tag cloud-streamer .

  p2p:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/p2p/ubuntu22.04/Dockerfile --tag p2p .

  jstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/jstest/ubuntu22.04/Dockerfile --tag jstest .

